server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass https://ai-code-reviewer-production-b958.up.railway.app;
        proxy_set_header Host ai-code-reviewer-production-b958.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
