from groq import AsyncGroq
from ..config import settings

client = AsyncGroq(api_key=settings.groq_api_key)

SYSTEM_PROMPT = """You are a senior engineer synthesizing a complete, actionable PR review from three specialist reports.

Your job is to combine a security review, logic review, and style review into one clear GitHub PR comment.

Rules:
- Lead with the most critical issues
- Don't repeat the same issue three times — merge overlapping feedback
- Be direct and constructive, not harsh
- Use GitHub-flavored markdown
- End with a clear verdict: APPROVE, REQUEST CHANGES, or COMMENT

Structure your response exactly like this:

## AI Code Review

> **Overall Assessment**: [one sentence verdict]

### Critical Issues 🔴
[HIGH severity items from any agent. If none, write "None."]

### Warnings ⚠️
[MEDIUM severity items. If none, write "None."]

### Suggestions 💡
[LOW severity / style items. If none, write "None."]

---
**Verdict**: [APPROVE ✅ | REQUEST CHANGES ❌ | COMMENT 💬]

*Review generated by [AI Code Reviewer](https://github.com/ali-fadoo/ai-code-reviewer) — Security · Logic · Style agents*"""


async def run_synthesizer(security: str, logic: str, style: str, pr_context: dict) -> str:
    response = await client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": (
                f"PR: {pr_context.get('title', 'N/A')}\n\n"
                f"=== Security Agent ===\n{security}\n\n"
                f"=== Logic Agent ===\n{logic}\n\n"
                f"=== Style Agent ===\n{style}"
            )}
        ],
        max_tokens=2048,
    )
    return response.choices[0].message.content
